### ISSUE TITLE
Nothing after perform the Docker Build 

### ISSUE THREAD

**Issue by GVA-Guillaume** [fabriziofiorucci/NGINX-NMS-Docker#1]
Hi Fabrizio like you ask me I will create an issue

I don't think it's come from your docker file layer, because this is the same with my own docker image layer

I tried several deployment scenarios 

1) the official click house docker layer
2) the official click house script deployment
3 the official clickhouse manual deployment of repository
4) the NMS clickhouse install package as dependency

nginx always start very well, and I also can use unprivileged start, it works fine
but clickhouse and nms services (core, acm, dpm, ingestion and integrations) doesn't tart.

 tried on Debian-slim trought the official nginx.com docker layer
tried on your own dockerfile.automated  and dockerfile.manual layer

the systemctl is automatically removed when we install nms packages, services they don't want to be recognized as services
I am able to start all the services manually with /usr/bin/nms-core /usr/bin/nms-acm server etc ...
the works, and finally I have a problem of licence

i a not able to get NMS started 

in your dockerfilebuld 

nms API Connectivity manager is not installed at all, nms services doesn't start 

your actual Docker layer build : 

FROM ubuntu:20.04

ARG BUILD_WITH_SECONDSIGHT=false
ARG ADD_ACM
ARG ADD_SM
ARG ADD_PUM

# Initial setup
RUN apt-get update && \
	DEBIAN_FRONTEND=noninteractive apt-get install -y -q build-essential git nano curl jq wget gawk \
		nginx lsb-release rsyslog systemd apt-transport-https ca-certificates netcat sudo && \
	mkdir -p /etc/ssl/nginx /deployment

COPY ./container/startNIM.sh /deployment/

RUN --mount=type=secret,id=nginx-crt,dst=/etc/ssl/nginx/nginx-repo.crt,mode=0644 \
        --mount=type=secret,id=nginx-key,dst=/etc/ssl/nginx/nginx-repo.key,mode=0644 \
	set -x \
	&& chmod +x /deployment/startNIM.sh \
	&& printf "deb https://pkgs.nginx.com/nms/ubuntu `lsb_release -cs` nginx-plus\n" | tee /etc/apt/sources.list.d/nms.list \
	&& wget -q -O /etc/apt/apt.conf.d/90pkgs-nginx https://cs.nginx.com/static/files/90pkgs-nginx \
	&& wget -O /tmp/nginx_signing.key https://cs.nginx.com/static/keys/nginx_signing.key \
	&& apt-key add /tmp/nginx_signing.key \
	&& mkdir -p /etc/ssl/nginx    
    COPY nms/nginx-repo.crt /etc/ssl/nginx
    COPY nms/nginx-repo.key /etc/ssl/nginx
	RUN apt-get update \
	&& apt-get install -y nms-instance-manager \
	&& curl -s http://hg.nginx.org/nginx.org/raw-file/tip/xml/en/security_advisories.xml > /usr/share/nms/cve.xml \
	# Optional API Connectivity Manager
	&& if [ "${ADD_ACM}" = "true" ] ; then \
	apt-get -y install nms-api-connectivity-manager; fi \
	# Optional Security Monitoring
	&& if [ "${ADD_SM}" = "true" ] ; then \
	apt-get -y install nms-sm; fi \
	# Optional WAF Policy Compiler
	&& if [ ! -z "${ADD_PUM}" ] ; then \
	apt-get -y install nms-nap-compiler-$ADD_PUM; fi
	RUN apt-get -y install nms-api-connectivity-manager

# Optional Second Sight
WORKDIR /deployment
RUN if [ "$BUILD_WITH_SECONDSIGHT" = "true" ] ; then \
        apt-get install -y -q build-essential python3-pip python3-dev python3-simplejson git nano curl && \
        pip3 install fastapi uvicorn requests clickhouse-driver python-dateutil flask && \
	touch /deployment/counter.enabled && \
	git clone https://github.com/F5Networks/SecondSight && \
	cp SecondSight/f5tt/app.py . && \
	cp SecondSight/f5tt/bigiq.py . && \
	cp SecondSight/f5tt/cveDB.py . && \
	cp SecondSight/f5tt/f5ttCH.py . && \
	cp SecondSight/f5tt/f5ttfs.py . && \
	cp SecondSight/f5tt/nms.py . && \
	cp SecondSight/f5tt/utils.py . && \
	rm -rf SecondSight; fi
	
WORKDIR /deployment
CMD /deployment/startNIM.sh

here the output : https://www.linkedin.com/dms/D4E06AQGupkvNqa_yTg/messaging-attachmentFile/0/1679484486201?m=AQJGFXNIqGHn2AAAAYcJGrN3_eTchsUry1GhM3v_EepWhVNnIZtpqKMrvQ&ne=1&v=beta&t=iY0GY0ndVK2OmFOvbvDGilnBUMcBs5YVwwXqFvkXnz0

**Comment by fabriziofiorucci** [comment]
Hello @GVA-Guillaume let me check this and I'll get back to you

**Comment by GVA-Guillaume** [comment]
i have a 502 error at this time, how I can put the licence on the NMS ?only this way : 


curl -s -X PUT -k https://examples.tld/api/platform/v1/license -u "admin:T »h1s1s4n3p4ss0rD -d '{ "desiredState": { "content": « 786YHY8YFIG...» }, "metadata": { "name": "license" } }' -H "Content-Type: application/json"

The authentication is good, but is there something wrong in the licence format (base64 -w0 nms-licence.lic)
RESULT : 

{
    "code": 502,
    "message": "Upstream Unavailable"
}
root@8ce6d7b5e342:/# , thank you

**Comment by fabriziofiorucci** [comment]
Hello, HTTP/502 means that some processes are not running properly on NGINX Management Suite. I'm in the process of building a docker-compose yaml file to start it up on Docker, I'll keep you posted

**Comment by GVA-Guillaume** [comment]
Hi Fabio, 

how are you, man ! 

finally I tried with your guide, I followed step by step, everything works fine, but nginx/nms gui are not reachable through ip

nim2.f5.ff.lan, 

3verl4571ng@shaula manifests %  kubectl get pods -n nginx-nim2 -o wide                                                                       
NAME                         READY   STATUS    RESTARTS   AGE   IP          NODE             NOMINATED NODE   READINESS GATES
clickhouse-768bb5fb4-cxc8c   1/1     Running   0          97m   10.1.0.98   docker-desktop   <none>           <none>
grafana-7775b55bd4-sj762     1/1     Running   0          97m   10.1.0.99   docker-desktop   <none>           <none>
nginx-nim2-6b7d5f7f8-g5hn8   1/1     Running   0          97m   10.1.0.97   docker-desktop   <none>           <none>


root@nginx-nim2-6b7d5f7f8-g5hn8:/deployment# ps aufx
USER       PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
root      1414  0.1  0.0   4252  3608 pts/1    Ss   17:22   0:00 bash
root      1425  0.0  0.0   5908  2840 pts/1    R+   17:23   0:00  \_ ps aufx
root       204  0.0  0.0   2620   600 pts/0    Ss   15:52   0:00 /bin/sh
root       210  0.0  0.0   4252  3600 pts/0    S+   15:52   0:00  \_ bash
root         1  0.0  0.0   2620   604 ?        Ss   15:46   0:00 /bin/sh -c /deployment/startNIM.sh
root         7  0.0  0.0   4088  3204 ?        S    15:46   0:00 /bin/bash /deployment/startNIM.sh
root        71  0.1  0.7 782944 43696 ?        Sl   15:46   0:09  \_ /usr/bin/nms-core
root       102  0.5  0.9 792768 56584 ?        Sl   15:46   0:31  \_ /usr/bin/nms-dpm
root       118  0.2  0.5 748280 32596 ?        Sl   15:46   0:15  \_ /usr/bin/nms-ingestion
root       149  0.0  0.4 769032 25548 ?        Sl   15:46   0:03  \_ /usr/bin/nms-integrations
root       166  0.0  0.7 1441248 42808 ?       Sl   15:46   0:05  \_ /usr/bin/nms-acm server
root      1406  0.0  0.0   2520   524 ?        S    17:22   0:00  \_ sleep 60
root        44  0.0  0.0  82988  2028 ?        Ss   15:46   0:00 nginx: master process /usr/sbin/nginx
www-data    45  0.0  0.0  83156  3720 ?        S    15:46   0:00  \_ nginx: worker process
www-data    46  0.0  0.1  83484  7220 ?        S    15:46   0:00  \_ nginx: worker process

**Comment by GVA-Guillaume** [comment]
I created a Docker-compose with the Three Image targeted in this deployment and it works fine 

services: 
  storage:
    image: clickhouse
    container_name: clickhouse
  Instance:
    image: nim2
    #image: nginxp-globalch
    container_name: nim2
    ports:
      - 80:80
      - 443:443

  dashboard:
    image: grafana
    container_name: grafana

**Comment by fabriziofiorucci** [comment]
Thank you for your update! What about creating a pull request to merge your docker-compose deployment?

**Comment by GVA-Guillaume** [comment]
I don't think I can
<img width="1248" alt="Capture d’écran 2023-03-27 à 10 49 38" src="https://user-images.githubusercontent.com/128600399/227891377-adae060b-abdf-48f6-b237-005e90e3e7ec.png">

**Comment by fabriziofiorucci** [comment]
Have you tried forking the repository, applying all changes to your forked copy and creating a pull request from there? That should work
