### ISSUE TITLE
Yeah ! It's almost done 

### ISSUE THREAD

**Issue by GVA-Guillaume** [fabriziofiorucci/NGINX-NMS-Docker#2]
Hi Fab, hope your are doing good :)

I fixed the little baby by escaping from Kubernetes, so 

I started from the Docker.automated image, adding the protect functions, and a version with the agent.

At the base I wanted to implement a version integrating VAULT and CLICKHOUSE, but I'm still struggling a bit with the notion of final launcher in ENTRYPOINT or CMD, I would have to build a single boot file, I think.

So I start from Docker.automated, reviewed,

I adopt a docker-compose with the elements

vault and clickhouse elements.

the nim2 central image is launched with the startNIM.sh

In my docker-compose I can add a file: env or environments: 

NIM_CLICKHOUSE_ADDR NIM_CLICKHOUSE_PRT information

the file /etc/nms/nms.conf we see the information added at the bottom of the file.

Curious thing, when I leave the file in the container, everything works fine.

when I take the file out of the container to mount it in volume .../nms.conf:/etc/nms/nms.conf

I have a file parsing error like yaml unmarshall error, I wish we could look at this together, this is my last blocking point on nms.

I'm still working on the last crucial point: secure connections to port 9440 on the clickhouse and 8201 on the vault.

Thanks (I planned to share soon, my work)

Compose fie 👍 

services: 
  vault:
    image:  vault
    container_name: vault
    #env_file:
     # - ./settings/vlt.env
    ports:
      - ...:8200
      - ...:8201
    volumes:
      - ./mounted/consul/consul.d:/etc/consul.d
      - ./mounted/vault/vault.d:/etc/vault.d
      - ./mounted/vault/home:/vault
    cap_add:
      - IPC_LOCK
    restart: always 
  clickhouse:
    image: clickhouse
    container_name: clickhouse
    env_file:
      - ./settings/clh.env
    ports:
      - ...:9000
      - ...:9440
    volumes:
       - .../log/:/var/log/clickhouse/
      - .../config.d/docker_related_config.xml:/etc/clickhouse-server/config.d/docker_related_config.xml
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
  nms:
    image: nim2
    container_name: nim2
    env_file:
      - .../env.env
    ports:
      - ...:80
      - ...:443
      - ...:8080
    volumes:
      - .../nms.conf:/etc/nms/nms.conf >> when I comment this it works, when I active this it does not bind because it does not parse the file

env.env file 👍 
NIM_USERNAME=U...
NIM_PASSWORD=P...
NIM_LICENSE=T...
NIM_CLICKHOUSE_ADDRESS=clickhouse
NIM_CLICKHOUSE_PORT=9000
NIM_CLICKHOUSE_USERNAME=U...
NIM_CLICKHOUSE_PASSWORD=P...

**Comment by fabriziofiorucci** [comment]
Hi Guillaume,

FYI docker-compose has been added to the repo:

https://github.com/fabriziofiorucci/NGINX-NMS-Docker/tree/main/contrib/docker-compose

**Comment by GVA-Guillaume** [comment]
The very cool, Fab, it was something I did, I have to compare and publish my works
